#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh
HELM="$SNAP/helm3.wrapper"
KUBECTL="$SNAP/kubectl.wrapper"
OPENEBS_NS="openebs"

echo "Disabling OpenEBS"

disable_openebs() {

    $HELM -n $OPENEBS_NS uninstall openebs
    $KUBECTL delete namespace $OPENEBS_NS

    echo "OpenEBS disabled"
    echo "Manually clean up the directory $SNAP_COMMON/var/openebs/"
}


disable_openebs
